'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EntranceExamApplication.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _14823926_beautiful_student_girl_with_books_isolated_on_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14823926-beautiful-student-girl-with-books-isolated-on-white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject(",m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_procedures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_procedures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copy__3__of_PH01179J() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy (3) of PH01179J", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copy_of_Success() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy of Success", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property discussing2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discussing2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property entrance_banner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("entrance-banner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Executive_MBA_300x211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Executive-MBA-300x211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imag4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imag4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageshb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageshb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imagesw1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagesw1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indexq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indexq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property internet_635() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet_635", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock_key_security_concept_keyboard_33384268() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock-key-security-concept-keyboard-33384268", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock_key_security_concept_keyboard_333842681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock-key-security-concept-keyboard-333842681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property online_exam_940x196() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("online-exam-940x196", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property slider_photo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slider_photo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property slider_photo31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slider_photo31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property th() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
